function cfg = dp_defaults(model)
%DP_DEFAULTS Build a complete default configuration struct for the application.
%
% Creates and returns the cfg structure that centralizes all baseline settings
% used across the project: model name, physical parameters, simulation step,
% equilibrium/reference selection, initial conditions, LQR tuning defaults,
% hysteresis thresholds, and workspace export mode. This function defines the
% "starting point" for the app so that initialization and resets are
% repeatable and do not depend on scattered hardcoded values.
%
% Input:
%   model - (optional) Simulink model name; defaults to 'model' when omitted.
%
% Output:
%   cfg - struct containing nested sections: p, sim, eq, ic, lqr, hyst, export.

if nargin < 1 || isempty(model)
    model = 'model';
end

cfg = struct();
cfg.mdl = model;

% physical parameters
cfg.p = struct( ...
    'M',  1.0, ...
    'm1', 0.10, ...
    'm2', 0.10, ...
    'l1', 0.50, ...
    'l2', 0.50, ...
    'g',  9.81, ...
    'b',  0.0, ...
    'c1', 0.0, ...
    'c2', 0.0 ...
    );

% simulation
cfg.sim = struct('Ts', 0.005);

% equilibrium / reference
cfg.eq = struct( ...
    'mode', 1, ...          % 1..4
    'useMode', true, ...
    'x_ref', 0, ...
    'theta1e', 0, ...
    'theta2e', 0 ...
    );

% initial conditions
cfg.ic = struct( ...
    'x0', 0, ...
    'theta1_0', 0, ...
    'theta2_0', 0 ...
    );

% LQR
cfg.lqr = struct( ...
    'Qdiag', [10 10 200 10 200 10], ...
    'R', 10 ...
    );

% hysteresis
cfg.hyst = struct( ...
    'th_on', -0.2, ...
    'delta', 0.3, ...
    'enabled', true ...
    );

cfg.export = 'base'; % 'base' | 'model' | 'both'
end
