function cfg = dp_defaults(model)
%DP_DEFAULTS Deterministic default configuration for the model/app.

    if nargin < 1 || isempty(model)
        model = 'model';
    end

    cfg = struct();
    cfg.mdl = model;

    % physical parameters
    cfg.p = struct( ...
        'M',  1.0, ...
        'm1', 0.10, ...
        'm2', 0.10, ...
        'l1', 0.50, ...
        'l2', 0.50, ...
        'g',  9.81, ...
        'b',  0.0, ...
        'c1', 0.0, ...
        'c2', 0.0 ...
    );

    % simulation
    cfg.sim = struct('Ts', 0.005);

    % equilibrium / reference
    cfg.eq = struct( ...
        'mode', 1, ...          % 1..4
        'useMode', true, ...
        'x_ref', 0, ...
        'theta1e', 0, ...
        'theta2e', 0 ...
    );

    % initial conditions
    cfg.ic = struct( ...
        'x0', 0, ...
        'theta1_0', 0, ...
        'theta2_0', 0 ...
    );

    % LQR
    cfg.lqr = struct( ...
        'Qdiag', [10 10 200 10 200 10], ...
        'R', 10 ...
    );

    % hysteresis (swingup/LQR switch)
    cfg.hyst = struct( ...
        'th_on', -0.2, ...
        'delta', 0.3, ...
        'enabled', true ...
    );

    % export target
    cfg.export = 'base'; % 'base' | 'model' | 'both'
end
