function ui = ui_build_params(parent, fig, cfg)
%UI_BUILD_PARAMS Build the parameter panel UI (model constants, LQR, hysteresis) and return handles.
%
% Creates uicontrol/uipanel elements under the given parent container, initializes
% them from cfg (or defaults), and wires callbacks that update the app state.
% Returns a struct of UI handles used by the rest of the application.
%
% Inputs:
%   parent - graphics handle of the container (panel/figure) that hosts the controls.
%   fig    - handle to the main UI figure (used by callbacks for guidata access).
%   cfg    - (optional) configuration struct used to initialize control values.
%
% Output:
%   ui - struct containing handles to created UI controls and panels.

if nargin < 3 || isempty(cfg)
    try
        cfg = dp_defaults('model');
    catch
        cfg = struct();
    end
end

bg = get(parent,'BackgroundColor');
ui = struct();

ui.btnResetAll = uicontrol('Parent', parent, 'Style','pushbutton', 'Units','normalized', ...
    'Position',[0.78 0.93 0.18 0.06], 'String','Domyślne', ...
    'Callback', @(~,~)ui_reset_defaults(fig));

ui.btnTheory = uicontrol('Parent', parent, 'Style','pushbutton', 'Units','normalized', ...
    'Position',[0.78 0.86 0.18 0.06], 'String','Opis', ...
    'Callback', @(~,~)ui_open_theory(fig));

ui.txtEq = uicontrol('Parent', parent, 'Style','text', 'Units','normalized', ...
    'Position',[0.04 0.92 0.72 0.06], ...
    'String','Balansowanie wokół: x = 0, θ₁ = 0 rad, θ₂ = 0 rad', ...
    'HorizontalAlignment','left', 'BackgroundColor', bg);

uicontrol('Parent', parent, 'Style','text', 'Units','normalized', ...
    'Position',[0.04 0.86 0.36 0.05], 'String','Współczynnik zaburzenia', ...
    'HorizontalAlignment','left', 'BackgroundColor', bg);

ui.edtKickAmp = uicontrol('Parent', parent, 'Style','edit', 'Units','normalized', ...
    'Position',[0.42 0.855 0.18 0.06], ...
    'String', num2str(safeCfg(cfg,'kick','amp',70)), ...
    'Callback', @(~,~)ui_update_kick(fig));

pModel = uipanel('Parent', parent, 'Units','normalized', ...
    'Position',[0.04 0.66 0.92 0.16], 'Title','Stałe modelu');

bgM = get(pModel,'BackgroundColor');

uicontrol('Parent', pModel, 'Style','text', 'Units','normalized', ...
    'Position',[0.04 0.52 0.16 0.32], 'String','Stałe modelu:', ...
    'HorizontalAlignment','left', 'BackgroundColor', bgM);

ui.hP = gobjects(1,6);

vals = [ ...
    safeCfg(cfg,'p','M', 1.0), ...
    safeCfg(cfg,'p','m1',0.10), ...
    safeCfg(cfg,'p','m2',0.10), ...
    safeCfg(cfg,'p','l1',0.50), ...
    safeCfg(cfg,'p','l2',0.50), ...
    safeCfg(cfg,'p','g', 9.81) ...
    ];
init = arrayfun(@(x)num2str(x), vals(:).', 'UniformOutput', false);

x0 = 0.22; y0 = 0.52; w = 0.115; h = 0.32; gap = 0.012;

for i = 1:6
    ui.hP(i) = uicontrol('Parent', pModel, 'Style','edit', 'Units','normalized', ...
        'Position',[x0+(i-1)*(w+gap) y0 w h], ...
        'String', init{i}, ...
        'Callback', @(~,~)ui_update_model_consts(fig));
end

labelsP = {'M','m1','m2','l1','l2','g'};
for i = 1:6
    uicontrol('Parent', pModel, 'Style','text', 'Units','normalized', ...
        'Position',[x0+(i-1)*(w+gap) 0.18 w 0.22], ...
        'String', labelsP{i}, ...
        'HorizontalAlignment','center', ...
        'BackgroundColor', bgM);
end

pLqr = uipanel('Parent', parent, 'Units','normalized', ...
    'Position',[0.04 0.32 0.92 0.32], 'Title','LQR - Q, R, K');

uicontrol('Parent', pLqr, 'Style','text', 'Units','normalized', ...
    'Position',[0.04 0.72 0.10 0.16], 'String','Q =', ...
    'HorizontalAlignment','left', 'BackgroundColor', get(pLqr,'BackgroundColor'));

ui.hQ = gobjects(1,6);
x0 = 0.16; y0 = 0.74; w = 0.12; h = 0.16; gap = 0.02;
q0 = safeCfg(cfg,'lqr','Qdiag',[10 10 200 10 200 10]);
qInit = arrayfun(@(x)num2str(x), q0(:).', 'UniformOutput', false);
for i = 1:6
    ui.hQ(i) = uicontrol('Parent', pLqr, 'Style','edit', 'Units','normalized', ...
        'Position',[x0+(i-1)*(w+gap) y0 w h], ...
        'String', qInit{i}, ...
        'Callback', @(~,~)ui_update_lqr(fig));
end

labels = {'θ₀','θ̇₀','θ₁','θ̇₁','θ₂','θ̇₂'};
for i = 1:6
    uicontrol('Parent', pLqr, 'Style','text', 'Units','normalized', ...
        'Position',[x0+(i-1)*(w+gap) 0.60 w 0.10], ...
        'String', labels{i}, ...
        'HorizontalAlignment','center', ...
        'BackgroundColor', get(pLqr,'BackgroundColor'));
end

uicontrol('Parent', pLqr, 'Style','text', 'Units','normalized', ...
    'Position',[0.04 0.40 0.10 0.14], 'String','R =', ...
    'HorizontalAlignment','left', 'BackgroundColor', get(pLqr,'BackgroundColor'));

ui.edtR = uicontrol('Parent', pLqr, 'Style','edit', 'Units','normalized', ...
    'Position',[0.16 0.40 0.20 0.14], 'String', num2str(safeCfg(cfg,'lqr','R',100)), ...
    'Callback', @(~,~)ui_update_lqr(fig));

ui.txtK = uicontrol('Parent', pLqr, 'Style','text', 'Units','normalized', ...
    'Position',[0.04 0.04 0.92 0.20], ...
    'String','K = [ - ]', ...
    'HorizontalAlignment','left', ...
    'BackgroundColor', get(pLqr,'BackgroundColor'));

pH = uipanel('Parent', parent, 'Units','normalized', ...
    'Position',[0.04 0.06 0.92 0.24], 'Title','Przełączanie - histereza (Relay)');

bgH = get(pH,'BackgroundColor');

uicontrol('Parent', pH, 'Style','text', 'Units','normalized', ...
    'Position',[0.04 0.68 0.36 0.18], 'String','Punkt włączenia' , ...
    'HorizontalAlignment','left', 'BackgroundColor', get(pH,'BackgroundColor'));

ui.edtThOn = uicontrol('Parent', pH, 'Style','edit', 'Units','normalized', ...
    'Position',[0.42 0.66 0.18 0.22], 'String', num2str(safeCfg(cfg,'hyst','th_on',-0.2)), ...
    'Callback', @(~,~)ui_update_hysteresis(fig));

uicontrol('Parent', pH, 'Style','text', 'Units','normalized', ...
    'Position',[0.04 0.43 0.36 0.18], 'String','Szerokość histerezy Δ', ...
    'HorizontalAlignment','left', 'BackgroundColor', bgH);

ui.edtDelta = uicontrol('Parent', pH, 'Style','edit', 'Units','normalized', ...
    'Position',[0.42 0.41 0.18 0.22], 'String', num2str(safeCfg(cfg,'hyst','delta',0.3)), ...
    'Callback', @(~,~)ui_update_hysteresis(fig));

uicontrol('Parent', pH, 'Style','text', 'Units','normalized', ...
    'Position',[0.04 0.21 0.36 0.18], 'String','Punkt wyłączenia = on - Δ', ...
    'HorizontalAlignment','left', 'BackgroundColor', bgH);

ui.edtThOff = uicontrol('Parent', pH, 'Style','text', 'Units','normalized', ...
    'Position',[0.42 0.21 0.18 0.18], 'HorizontalAlignment','left', ...
    'BackgroundColor', bgH);

ui.btnHystPlot = uicontrol('Parent', pH, 'Style','pushbutton', 'Units','normalized', ...
    'Position',[0.72 0.10 0.24 0.26], 'String','wykres', ...
    'FontSize', 9);

end

function v = safeCfg(cfg, section, field, fallback)
v = fallback;
try
    if isstruct(cfg) && isfield(cfg,section) && isstruct(cfg.(section)) && isfield(cfg.(section),field)
        v = cfg.(section).(field);
    end
catch
end
end
