function ui = ui_build_params(parent, fig, cfg)
    if nargin < 3 || isempty(cfg)
        try
            cfg = dp_defaults('model');
        catch
            cfg = struct();
        end
    end

    bg = get(parent,'BackgroundColor');
    ui = struct();

    % Reset domyślnych ustawień w prawym górnym rogu panelu "Parametry"
    ui.btnResetAll = uicontrol('Parent', parent, 'Style','pushbutton', 'Units','normalized', ...
        'Position',[0.78 0.93 0.18 0.06], 'String','Reset domyślne', ...
        'Callback', @(~,~)ui_reset_defaults(fig));

    ui.txtEq = uicontrol('Parent', parent, 'Style','text', 'Units','normalized', ...
        'Position',[0.04 0.92 0.72 0.06], ...
        'String','Balansowanie wokół: x = 0, θ₁ = 0 rad, θ₂ = 0 rad', ...
        'HorizontalAlignment','left', 'BackgroundColor', bg);

    % --- Stałe modelu (edytowalne) ---
    % Uwaga: zbyt małe panele powodują, że uicontrol-e dostają minimalną wysokość
    % w pikselach i zaczynają się nachodzić / „ucinać”. Dlatego pilnujemy tu
    % bezpiecznych wysokości paneli, a „pustkę” redukujemy układem wewnętrznym.
    pModel = uipanel('Parent', parent, 'Units','normalized', ...
        'Position',[0.04 0.74 0.92 0.16], 'Title','Stałe modelu');

    bgM = get(pModel,'BackgroundColor');

    % Układ jak w LQR (etykieta + 6 pól), ale dopasowany rozmiarem do pól Q
    uicontrol('Parent', pModel, 'Style','text', 'Units','normalized', ...
        'Position',[0.04 0.52 0.16 0.32], 'String','Stałe modelu:', ...
        'HorizontalAlignment','left', 'BackgroundColor', bgM);

    ui.hP = gobjects(1,6);

    vals = [ ...
        safeCfg(cfg,'p','M', 1.0), ...
        safeCfg(cfg,'p','m1',0.10), ...
        safeCfg(cfg,'p','m2',0.10), ...
        safeCfg(cfg,'p','l1',0.50), ...
        safeCfg(cfg,'p','l2',0.50), ...
        safeCfg(cfg,'p','g', 9.81) ...
    ];
    init = arrayfun(@(x)num2str(x), vals(:).', 'UniformOutput', false);

    % Wymiary tak, żeby pola były podobne do LQR (Q) i mieściły się w panelu
    x0 = 0.22; y0 = 0.52; w = 0.115; h = 0.32; gap = 0.012;

    for i = 1:6
        ui.hP(i) = uicontrol('Parent', pModel, 'Style','edit', 'Units','normalized', ...
            'Position',[x0+(i-1)*(w+gap) y0 w h], ...
            'String', init{i}, ...
            'Callback', @(~,~)ui_update_model_consts(fig));
    end

    labelsP = {'M','m1','m2','l1','l2','g'};
    for i = 1:6
        uicontrol('Parent', pModel, 'Style','text', 'Units','normalized', ...
            'Position',[x0+(i-1)*(w+gap) 0.18 w 0.22], ...
            'String', labelsP{i}, ...
            'HorizontalAlignment','center', ...
            'BackgroundColor', bgM);
    end

    % LQR
    pLqr = uipanel('Parent', parent, 'Units','normalized', ...
        'Position',[0.04 0.42 0.92 0.30], 'Title','LQR - Q, R, K');

    uicontrol('Parent', pLqr, 'Style','text', 'Units','normalized', ...
        'Position',[0.04 0.72 0.10 0.16], 'String','Q =', ...
        'HorizontalAlignment','left', 'BackgroundColor', get(pLqr,'BackgroundColor'));

    ui.hQ = gobjects(1,6);
    x0 = 0.16; y0 = 0.74; w = 0.12; h = 0.16; gap = 0.02;
    q0 = safeCfg(cfg,'lqr','Qdiag',[200 50 200 10 10 10]);
    qInit = arrayfun(@(x)num2str(x), q0(:).', 'UniformOutput', false);
    for i = 1:6
        ui.hQ(i) = uicontrol('Parent', pLqr, 'Style','edit', 'Units','normalized', ...
            'Position',[x0+(i-1)*(w+gap) y0 w h], ...
            'String', qInit{i}, ...
            'Callback', @(~,~)ui_update_lqr(fig));
    end

    labels = {'x','ẋ','θ₁','θ̇₁','θ₂','θ̇₂'};
    for i = 1:6
        uicontrol('Parent', pLqr, 'Style','text', 'Units','normalized', ...
            'Position',[x0+(i-1)*(w+gap) 0.60 w 0.10], ...
            'String', labels{i}, ...
            'HorizontalAlignment','center', ...
            'BackgroundColor', get(pLqr,'BackgroundColor'));
    end

    uicontrol('Parent', pLqr, 'Style','text', 'Units','normalized', ...
        'Position',[0.04 0.42 0.10 0.14], 'String','R =', ...
        'HorizontalAlignment','left', 'BackgroundColor', get(pLqr,'BackgroundColor'));

    ui.edtR = uicontrol('Parent', pLqr, 'Style','edit', 'Units','normalized', ...
        'Position',[0.16 0.44 0.20 0.14], 'String', num2str(safeCfg(cfg,'lqr','R',100)), ...
        'Callback', @(~,~)ui_update_lqr(fig));

    ui.txtK = uicontrol('Parent', pLqr, 'Style','text', 'Units','normalized', ...
        'Position',[0.04 0.10 0.92 0.24], ...
        'String','K = [ - ]', ...
        'HorizontalAlignment','left', ...
        'BackgroundColor', get(pLqr,'BackgroundColor'));

    % Histereza (bez osi)
    pH = uipanel('Parent', parent, 'Units','normalized', ...
        'Position',[0.04 0.06 0.92 0.34], 'Title','Przełączanie - histereza (Relay)');

    uicontrol('Parent', pH, 'Style','text', 'Units','normalized', ...
        'Position',[0.04 0.62 0.36 0.20], 'String','Switch on point' , ...
        'HorizontalAlignment','left', 'BackgroundColor', get(pH,'BackgroundColor'));

    ui.edtThOn = uicontrol('Parent', pH, 'Style','edit', 'Units','normalized', ...
        'Position',[0.42 0.62 0.18 0.24], 'String', num2str(safeCfg(cfg,'hyst','th_on',-0.2)), ...
        'Callback', @(~,~)ui_update_hysteresis(fig));

    uicontrol('Parent', pH, 'Style','text', 'Units','normalized', ...
        'Position',[0.62 0.62 0.22 0.20], 'String','Szerokość histerezy Δ' , ...
        'HorizontalAlignment','left', 'BackgroundColor', get(pH,'BackgroundColor'));

    ui.edtDelta = uicontrol('Parent', pH, 'Style','edit', 'Units','normalized', ...
        'Position',[0.86 0.62 0.10 0.24], 'String', num2str(safeCfg(cfg,'hyst','delta',0.3)), ...
        'Callback', @(~,~)ui_update_hysteresis(fig));

    uicontrol('Parent', pH, 'Style','text', 'Units','normalized', ...
        'Position',[0.04 0.18 0.42 0.20], 'String','Switch off point = on - Δ' , ...
        'HorizontalAlignment','left', 'BackgroundColor', get(pH,'BackgroundColor'));

    thOn0 = safeCfg(cfg,'hyst','th_on',-0.2);
    d0 = safeCfg(cfg,'hyst','delta',0.3);
    ui.edtThOff = uicontrol('Parent', pH, 'Style','edit', 'Units','normalized', ...
        'Position',[0.42 0.18 0.18 0.24], 'String', num2str(thOn0 - d0), ...
        'Enable','inactive');

    % mały, subtelny przycisk
    ui.btnHystPlot = uicontrol('Parent', pH, 'Style','pushbutton', 'Units','normalized', ...
        'Position',[0.72 0.18 0.24 0.24], 'String','wykres', ...
        'FontSize', 8);

end

function v = safeCfg(cfg, section, field, fallback)
    v = fallback;
    try
        if isstruct(cfg) && isfield(cfg,section) && isstruct(cfg.(section)) && isfield(cfg.(section),field)
            v = cfg.(section).(field);
        end
    catch
    end
end
